version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - env/.env.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enables hot reloading inside Docker
    stdin_open: true  # Equivalent to -i in docker run
    tty: true  # Equivalent to -t in docker run
