services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - /app/node_modules
    env_file:
      - env/.env.dev
    environment:
      - ESLINT_NO_DEV_ERRORS=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000
    stdin_open: true
    tty: true
    restart: unless-stopped
