apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  connection-string: bW9uZ29kYitzcnY6Ly9iaW9uZGluYW1hdHRoaWpzOmkwU1BmSXp1WlBUUTBSbjhAY2x1c3RlcjAua3ltbG0ubW9uZ29kYi5uZXQ/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjAgLW4K
