apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: authentication:dev
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "800m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "512Mi"
