FROM node:22-alpine
WORKDIR /app
# Copy package files first to leverage Docker caching
COPY package.json package-lock.json* ./
# Install dependencies
RUN npm install --legacy-peer-deps
# Copy the rest of the application code
COPY . .
# Expose port
EXPOSE 3000
EXPOSE 9229
# Start the development server with inspector enabled
CMD ["npm", "run", "debug"]
