apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-gateway
  labels:
    app: public-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-gateway
  template:
    metadata:
      labels:
        app: public-gateway
    spec:
      containers:
      - name: public-gateway
        image: public-gateway:dev
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "800m"
            memory: "1024Mi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
        - name: firebase-credentials
          mountPath: "/app/firebase-service-account.json"
          subPath: "firebase-service-account.json"
          readOnly: true
      volumes:
      - name: firebase-credentials
        secret:
          secretName: firebase-credentials
