version: '3.8'

services:
  backend:
    network_mode: "host"
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app
      - /app/__pycache__/
    env_file:
      - env/.env.dev
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload

networks:
  app-network:
    driver: bridge
