version: "3.8"

services:
  backend:
    network_mode: "host"
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app
      - /app/__pycache__/
    env_file:
      - env/.env.dev
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - BACKEND_URL=${NGROK_URL}
    depends_on:
      - ngrok
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload

  ngrok:
    network_mode: "host"
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: "http localhost:5000"

  mailhog:
    network_mode: "host"
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
