apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: users:dev
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: connection-string
          resources:
            limits:
              cpu: "800m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "512Mi"
