apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
type: Opaque
data:
  connection-string: bW9uZ29kYitzcnY6Ly9iaW9uZGluYW1hdHRoaWpzOmkwU1BmSXp1WlBUUTBSbjhAY2x1c3RlcjAua3ltbG0ubW9uZ29kYi5uZXQvdXNlci1zZXJ2aWNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
