apiVersion: v1
kind: Service
metadata:
  name: expo-app
  labels:
    app: expo-app
spec:
  type: NodePort
  ports:
  - port: 19000
    targetPort: 19000
    nodePort: 30100
    name: expo-app
  - port: 19001
    targetPort: 19001
    nodePort: 30101
    name: expo-bundle
  - port: 19002
    targetPort: 19002
    nodePort: 30102
    name: expo-devtools
  selector:
    app: expo-app
