services:
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "9230:9229"
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - ../frontend/env/.env.dev
    environment:
      - CI=true
      - ESLINT_NO_DEV_ERRORS=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: ["npm", "run", "debug"]

  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - ../backend:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - ../backend/env/.env.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    command: ["npm", "run", "debug"]

volumes:
  frontend_node_modules:
  backend_node_modules:
