services:
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "9230:9229"
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - ../frontend/env/.env.dev
    environment:
      - CI=true
      - ESLINT_NO_DEV_ERRORS=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: ["npm", "run", "debug"]
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"  # Changed from 5000 to 8000 for FastAPI
      - "5678:5678"  # Port for debugpy
    volumes:
      - ../backend:/app
      - /app/__pycache__/  # Ignore Python cache
    env_file:
      - ../backend/env/.env.dev
    environment:
      - PYTHONUNBUFFERED=1  # Ensures Python output is sent straight to terminal
      - PYTHONDONTWRITEBYTECODE=1  # Prevents Python from writing .pyc files
    restart: unless-stopped
    # Command that enables the debugger but still starts the application
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
volumes:
  frontend_node_modules:
